name: io
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - libedit=3.1.20181209
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2
  - python=3.7.7
  - readline=8.0
  - setuptools=46.4.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cachetools==4.1.0
    - chardet==3.0.4
    - google-api-core==1.17.0
    - google-api-python-client==1.8.3
    - google-auth==1.15.0
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.51.0
    - gspread==3.6.0
    - httplib2==0.18.1
    - idna==2.9
    - numpy==1.18.4
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - pandas==1.0.3
    - protobuf==3.12.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.1
    - pytz==2020.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - six==1.14.0
    - uritemplate==3.0.1
    - urllib3==1.25.9

