version: 2
jobs:
    build_run_docker_test:
        machine:
            image: hbclab/intervention-outcomes-env:v1.0.0
        working_directory: /home/coder/projects
        steps:
            - checkout
            
            - run:
                name: build and run docker image testing
                no_output_timeout: 60m
                command: |
                    conda activate io
                    echo $CREDENTIALS > credentials.json
                    /home/coder/projects/validation/run.sh $DOCID $NAME_ACC $TOKEN_ACC $SECRET_ACC $APPID_DEPLOY $APPNAME_DEPLOY
    build_run_docker_prod:
        machine:
            image: hbclab/intervention-outcomes-env:v1.0.0
        working_directory: /home/coder/projects
        steps:
            - checkout
            - run:
                name: build and run docker image production
                no_output_timeout: 60m
                command: |
                    conda activate io
                    echo $CREDENTIALS > credentials.json
                    /home/coder/projects/validation/run.sh $DOCID $NAME_ACC $TOKEN_ACC $SECRET_ACC $APPID_DEPLOY_PROD $APPNAME_DEPLOY_PROD
workflows:
    version: 2
    build_run_test:
        jobs:
            - build_run_docker_test:
                filters:
                    branches:
                        ignore:
                            - master
    weekly_data_update:
        jobs:
            - build_run_docker_prod
        triggers:
            - schedule:
                cron: "0 0 * * 0"
                filters:
                    branches:
                        only:
                            - master